### ISSUE TITLE
dnndk下载地址似乎已经失效

### ISSUE THREAD

**Issue by lavender37** [wutianze/dnndk-pynqz2#10]
参考build-host-dnndk.md文件中的dnndk_v3.0下载地址，但是链接已经失效无法下载，将我重定向到https://www.xilinx.com/support/download.html，但是我已经登录xilinx，我看到下载链接是
https://www.xilinx.com/member/forms/download/dnndk-eula-xef.html?filename=xlnx_dnndk_v3.0_190624.tar.gz
，请问是否还有其它方式能够下载，或者下载链接有误

**Comment by wutianze** [comment]
那就直接在xilinx官网上找吧，反正只要是dnndk v3.0的就行




------------------&nbsp;Original&nbsp;------------------

**Comment by lavender37** [comment]
官网翻了一圈没找到，请问你还有dnndk的存档吗

**Comment by wutianze** [comment]
> 官网翻了一圈没找到，请问你还有dnndk的存档吗

官网好像全面转vitis AI了，那就将就用一下https://pan.baidu.com/s/1gOJaoJJ8z2jf-BaLklID3Q#list/path=%2F或是https://drive.google.com/file/d/1vuwzj5Xu05-Jubmzv7Tkx-XbpLa_D_4q/view吧

**Comment by lavender37** [comment]
谢谢
