### ISSUE TITLE
安装包

### ISSUE THREAD

**Issue by wsnnnn** [wutianze/dnndk-pynqz2#11]
您好？我想问一下您还有DNNDK的安装包吗？官网的好像下架了，在网上也没找到。

**Comment by wutianze** [comment]
> 您好？我想问一下您还有DNNDK的安装包吗？官网的好像下架了，在网上也没找到。

的确是，这个只能等xilinx的消息了，我这没有额外的备份，听说vitis AI兼容DNNDK？

**Comment by wsnnnn** [comment]
谢谢了，我找到dnndk的安装包了。打算走一遍您的例程，然后再去试试vitis。感谢。



---原始邮件---
发件人: "sauron"<notifications@github.com&gt;
发送时间: 2020年10月20日(周二) 晚上10:05
收件人: "wutianze/dnndk-pynqz2"<dnndk-pynqz2@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"wsnnnn"<2910507650@qq.com&gt;;
主题: Re: [wutianze/dnndk-pynqz2] 安装包 (#11)




  
您好？我想问一下您还有DNNDK的安装包吗？官网的好像下架了，在网上也没找到。
  
的确是，这个只能等xilinx的消息了，我这没有额外的备份，听说vitis AI兼容DNNDK？

**Comment by lavender37** [comment]
> 谢谢了，我找到dnndk的安装包了。打算走一遍您的例程，然后再去试试vitis。感谢。
> […](#)
> ---原始邮件--- 发件人: "sauron"<notifications@github.com&gt; 发送时间: 2020年10月20日(周二) 晚上10:05 收件人: "wutianze/dnndk-pynqz2"<dnndk-pynqz2@noreply.github.com&gt;; 抄送: "Author"<author@noreply.github.com&gt;;"wsnnnn"<2910507650@qq.com&gt;; 主题: Re: [wutianze/dnndk-pynqz2] 安装包 (#11) 您好？我想问一下您还有DNNDK的安装包吗？官网的好像下架了，在网上也没找到。 的确是，这个只能等xilinx的消息了，我这没有额外的备份，听说vitis AI兼容DNNDK？ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

请问你是在哪里找到的，能分享一份吗

**Comment by wuweian** [comment]
@wsnnnn 
您好
我目前也在找 DNNDK v3.0 host 安裝包，看到您之前留言說已經找到 dnndk 的安装包了
想請問您當時是在哪裡找到的
如果方便的話，能否告知下載來源？
非常感謝

**Comment by wsnnnn** [comment]
您好，时间太久了，找不到了，不好意思。





---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2026年6月5日(周五) 晚上8:52
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [wutianze/dnndk-pynqz2] 安装包 (#11)


wuweian left a comment (wutianze/dnndk-pynqz2#11)
 
@wsnnnn
 您好
 我目前也在找 DNNDK v3.0 host 安裝包，看到您之前留言說已經找到 dnndk 的安装包了
 想請問您當時是在哪裡找到的
 如果方便的話，能否告知下載來源？
 非常感謝
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications, keep track of coding agent tasks and review pull requests on the go with GitHub Mobile for iOS and Android. Download it today!
