### ISSUE TITLE
[DNNDK] fail to open DPU device and exit ...

### ISSUE THREAD

**Issue by ghost** [wutianze/dnndk-pynqz2#12]
请问在Running Applications on PYNQ-Z2的步骤下，2和3步骤具体如何执行呀？
这个rootfs.tar.gz在哪里呀？
1. Copy `<PROJ ROOT>/pynq-z2-dpu/images/linux/image.ub`, `BOOT.BIN` and `rootfs.tar.gz` to the `sdcard` directory.

```
cp ./images/linux/BOOT.BIN /media/$(whoami)/BOOT/
cp ./images/linux/image.ub /media/$(whoami)/BOOT/
```

2. Extract `rootfs.tar.gz` to `rootfs` ext4 partition
```
tar xzf ./images/linux/rootfs.tar.gz -C /media/$(whoami)/rootfs/
```

3. Copy `yolo` and `dnndk` to the `sdcard` and sync.
```
cp -r ../sdcard/* /media/$(whoami)/rootfs/home/root/
sync

**Comment by wutianze** [comment]
> 请问在Running Applications on PYNQ-Z2的步骤下，2和3步骤具体如何执行呀？
> 这个rootfs.tar.gz在哪里呀？
> 
> 1. Copy `<PROJ ROOT>/pynq-z2-dpu/images/linux/image.ub`, `BOOT.BIN` and `rootfs.tar.gz` to the `sdcard` directory.
> 
> ```
> cp ./images/linux/BOOT.BIN /media/$(whoami)/BOOT/
> cp ./images/linux/image.ub /media/$(whoami)/BOOT/
> ```
> 
> 1. Extract `rootfs.tar.gz` to `rootfs` ext4 partition
> 
> ```
> tar xzf ./images/linux/rootfs.tar.gz -C /media/$(whoami)/rootfs/
> ```
> 
> 1. Copy `yolo` and `dnndk` to the `sdcard` and sync.
> 
> ```
> cp -r ../sdcard/* /media/$(whoami)/rootfs/home/root/
> sync
> ```

https://github.com/wutianze/dnndk-pynqz2/blob/master/build-pynqz2-system.md这里有提供相关文件的百度网盘下载链接，里面有

**Comment by ghost** [comment]
这个里面就只是一个镜像文件，我已经下载并烧录到sd卡了，能留个qq交流下吗？

**Comment by ghost** [comment]
烧录到sd卡后，根据你的Running Applications on PYNQ-Z2，我就不太明白你的Copy <PROJ ROOT>/pynq-z2-dpu/images/linux/image.ub, BOOT.BIN and rootfs.tar.gz to the sdcard directory.这是怎么执行的？是你的上位机里操作，还是在z2的系统里？

**Comment by wutianze** [comment]
> 烧录到sd卡后，根据你的Running Applications on PYNQ-Z2，我就不太明白你的Copy /pynq-z2-dpu/images/linux/image.ub, BOOT.BIN and rootfs.tar.gz to the sdcard directory.这是怎么执行的？是你的上位机里操作，还是在z2的系统里？

你直接下载镜像的话镜像里应该都已经拷贝好了，你只要最后检查一下sd卡里有没有这些文件即可。

**Comment by CUMTyc05181789** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wutianze/dnndk-pynqz2"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月21日(星期三) 下午2:19
收件人:&nbsp;"wutianze/dnndk-pynqz2"<dnndk-pynqz2@noreply.github.com&gt;;
抄送:&nbsp;"3099160167"<3099160167@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [wutianze/dnndk-pynqz2] [DNNDK] fail to open DPU device and exit ... (#12)





  
烧录到sd卡后，根据你的Running Applications on PYNQ-Z2，我就不太明白你的Copy /pynq-z2-dpu/images/linux/image.ub, BOOT.BIN and rootfs.tar.gz to the sdcard directory.这是怎么执行的？是你的上位机里操作，还是在z2的系统里？
  
你直接下载镜像的话镜像里应该都已经拷贝好了，你只要最后检查一下sd卡里有没有这些文件即可。

**Comment by ghost** [comment]
sd卡里应该没有rootfs.tar.gz，而且也无法cd到/home/root,管理员权限也不行，提示没有这个目录




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "sauron"<notifications@github.com&gt;; 
发送时间: 2020年10月21日(星期三) 下午2:19
收件人: "wutianze/dnndk-pynqz2"<dnndk-pynqz2@noreply.github.com&gt;; 
抄送: "3099160167"<3099160167@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [wutianze/dnndk-pynqz2] [DNNDK] fail to open DPU device and exit ... (#12)





  
烧录到sd卡后，根据你的Running Applications on PYNQ-Z2，我就不太明白你的Copy /pynq-z2-dpu/images/linux/image.ub, BOOT.BIN and rootfs.tar.gz to the sdcard directory.这是怎么执行的？是你的上位机里操作，还是在z2的系统里？
  
你直接下载镜像的话镜像里应该都已经拷贝好了，你只要最后检查一下sd卡里有没有这些文件即可。

**Comment by ghost** [comment]
我电脑上看sd卡里就boot.bin和image.ub

**Comment by ghost** [comment]
会不会是提供的镜像有点问题呀？😂

**Comment by wutianze** [comment]
> sd卡里应该没有rootfs.tar.gz，而且也无法cd到/home/root,管理员权限也不行，提示没有这个目录
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "sauron"<notifications@github.com&gt;; 发送时间: 2020年10月21日(星期三) 下午2:19 收件人: "wutianze/dnndk-pynqz2"<dnndk-pynqz2@noreply.github.com&gt;; 抄送: "3099160167"<3099160167@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 主题: Re: [wutianze/dnndk-pynqz2] [DNNDK] fail to open DPU device and exit ... (#12) 烧录到sd卡后，根据你的Running Applications on PYNQ-Z2，我就不太明白你的Copy /pynq-z2-dpu/images/linux/image.ub, BOOT.BIN and rootfs.tar.gz to the sdcard directory.这是怎么执行的？是你的上位机里操作，还是在z2的系统里？ 你直接下载镜像的话镜像里应该都已经拷贝好了，你只要最后检查一下sd卡里有没有这些文件即可。 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

那照着前面的流程做下来有生成rootfs.tar.gz吗

**Comment by wutianze** [comment]
> 会不会是提供的镜像有点问题呀？😂

我在项目首页提供了已经配置完的镜像，所以后来很少会有人从头build一遍，不知道你是否有拿到如图的这些文件。
![image](https://user-images.githubusercontent.com/13427786/96686113-afd3d780-13b0-11eb-89d8-7adf5a7312de.png)

**Comment by ghost** [comment]
> > 会不会是提供的镜像有点问题呀？😂
> 
> 我在项目首页提供了已经配置完的镜像，所以后来很少会有人从头build一遍，不知道你是否有拿到如图的这些文件。
> ![image](https://user-images.githubusercontent.com/13427786/96686113-afd3d780-13b0-11eb-89d8-7adf5a7312de.png)

我拿到的文件只有镜像以及github你上传的dnndk-pynqz2-master，没有图上大部分文件，图中的文件，boot.bin,image.ub和sdcard下的有，其他没有。

**Comment by wutianze** [comment]
> > > 会不会是提供的镜像有点问题呀？😂
> > 
> > 
> > 我在项目首页提供了已经配置完的镜像，所以后来很少会有人从头build一遍，不知道你是否有拿到如图的这些文件。
> > ![image](https://user-images.githubusercontent.com/13427786/96686113-afd3d780-13b0-11eb-89d8-7adf5a7312de.png)
> 
> 我拿到的文件只有镜像以及github你上传的dnndk-pynqz2-master，没有图上大部分文件，图中的文件，boot.bin,image.ub和sdcard下的有，其他没有。

你按照步骤用vivado做了吗？我感觉你前面的那些步骤是不是都没有做？其实如果你不是需要自己去定制dpu里的内容，可以直接下README里提供的镜像

**Comment by s1511215112** [comment]
我遇到的問題跟那位一樣
已經將xilinx-pynqz2-dpu3.0-pynq2.5.img燒進pynqz2裡面
![image](https://user-images.githubusercontent.com/74777370/105474087-d9b2d800-5cd8-11eb-826e-27379579c1fe.png)
但是沒有看到下面這張圖裡的文件
https://user-images.githubusercontent.com/13427786/96686113-afd3d780-13b0-11eb-89d8-7adf5a7312de.png
![image](https://user-images.githubusercontent.com/74777370/105474455-30b8ad00-5cd9-11eb-89dc-189f5c0db53a.png)

我接下來應該把以下3個資料夾放進pynqz2裡面嗎?
![image](https://user-images.githubusercontent.com/74777370/105474966-d1a76800-5cd9-11eb-9d9f-6308ab0c244c.png)


另外問個問題
我在jupyter_notebooks/resnet50 裡面找到
![image](https://user-images.githubusercontent.com/74777370/105475438-585c4500-5cda-11eb-87c1-e0ccb258bee8.png)

執行到resnet50_cn.ipynb中的 run DPU and get the result
![image](https://user-images.githubusercontent.com/74777370/105475765-b557fb00-5cda-11eb-9f79-5bed208b688c.png)
會造成
![執行dpu後內和死亡所以自動重啟](https://user-images.githubusercontent.com/74777370/105475809-c7d23480-5cda-11eb-8710-3656798ca093.JPG)
