### ISSUE TITLE
關於將img燒進pynqz2後該如何使用

### ISSUE THREAD

**Issue by s1511215112** [wutianze/dnndk-pynqz2#14]
我已經將xilinx-pynqz2-dpu3.0-pynq2.5.img燒進pynqz2裡面

![image](https://user-images.githubusercontent.com/74777370/105574235-1dbbe080-5d9e-11eb-812c-488a26af9baf.png)

但是沒有看到下面這張圖裡的文件

![image](https://user-images.githubusercontent.com/74777370/105574243-24e2ee80-5d9e-11eb-9b01-64b6122c8634.png)

我接下來應該把以下3個資料夾放進pynqz2裡面嗎?

![image](https://user-images.githubusercontent.com/74777370/105574244-29a7a280-5d9e-11eb-80b3-01cc3a1f9c56.png)

另外問個問題
我在jupyter_notebooks/resnet50 裡面找到

![image](https://user-images.githubusercontent.com/74777370/105574250-2f9d8380-5d9e-11eb-8fa1-a90b0c20b2ef.png)

執行到resnet50_cn.ipynb中的 run DPU and get the result

![image](https://user-images.githubusercontent.com/74777370/105574256-375d2800-5d9e-11eb-9b13-8f254ebdcb9c.png)

會造成
執行dpu後內核死亡所以自動重啟
![image](https://user-images.githubusercontent.com/74777370/105574259-42b05380-5d9e-11eb-94b1-b9461f907138.png)

我該如何使用這個dpu呢?

**Comment by wutianze** [comment]
> 我已經將xilinx-pynqz2-dpu3.0-pynq2.5.img燒進pynqz2裡面
> 
> ![image](https://user-images.githubusercontent.com/74777370/105574235-1dbbe080-5d9e-11eb-812c-488a26af9baf.png)
> 
> 但是沒有看到下面這張圖裡的文件
> 
> ![image](https://user-images.githubusercontent.com/74777370/105574243-24e2ee80-5d9e-11eb-9b01-64b6122c8634.png)
> 
> 我接下來應該把以下3個資料夾放進pynqz2裡面嗎?
> 
> ![image](https://user-images.githubusercontent.com/74777370/105574244-29a7a280-5d9e-11eb-80b3-01cc3a1f9c56.png)
> 
> 另外問個問題
> 我在jupyter_notebooks/resnet50 裡面找到
> 
> ![image](https://user-images.githubusercontent.com/74777370/105574250-2f9d8380-5d9e-11eb-8fa1-a90b0c20b2ef.png)
> 
> 執行到resnet50_cn.ipynb中的 run DPU and get the result
> 
> ![image](https://user-images.githubusercontent.com/74777370/105574256-375d2800-5d9e-11eb-9b13-8f254ebdcb9c.png)
> 
> 會造成
> 執行dpu後內核死亡所以自動重啟
> ![image](https://user-images.githubusercontent.com/74777370/105574259-42b05380-5d9e-11eb-94b1-b9461f907138.png)
> 
> 我該如何使用這個dpu呢?

如果你不是自己做镜像的话就不用管第一张图里那些文件了。如果是刚上手入门请按照文档的步骤来，等熟悉了再自己拓展。

**Comment by s1511215112** [comment]
> > 我已經將xilinx-pynqz2-dpu3.0-pynq2.5.img燒進pynqz2裡面
> > ![image](https://user-images.githubusercontent.com/74777370/105574235-1dbbe080-5d9e-11eb-812c-488a26af9baf.png)
> > 但是沒有看到下面這張圖裡的文件
> > ![image](https://user-images.githubusercontent.com/74777370/105574243-24e2ee80-5d9e-11eb-9b01-64b6122c8634.png)
> > 我接下來應該把以下3個資料夾放進pynqz2裡面嗎?
> > ![image](https://user-images.githubusercontent.com/74777370/105574244-29a7a280-5d9e-11eb-80b3-01cc3a1f9c56.png)
> > 另外問個問題
> > 我在jupyter_notebooks/resnet50 裡面找到
> > ![image](https://user-images.githubusercontent.com/74777370/105574250-2f9d8380-5d9e-11eb-8fa1-a90b0c20b2ef.png)
> > 執行到resnet50_cn.ipynb中的 run DPU and get the result
> > ![image](https://user-images.githubusercontent.com/74777370/105574256-375d2800-5d9e-11eb-9b13-8f254ebdcb9c.png)
> > 會造成
> > 執行dpu後內核死亡所以自動重啟
> > ![image](https://user-images.githubusercontent.com/74777370/105574259-42b05380-5d9e-11eb-94b1-b9461f907138.png)
> > 我該如何使用這個dpu呢?
> 
> 如果你不是自己做镜像的话就不用管第一张图里那些文件了。如果是刚上手入门请按照文档的步骤来，等熟悉了再自己拓展。

我照您的意見看了dnndk-pynqz2/mnist_tf/mnist_handwriting_guide.md這篇

前置作業為
Ubuntu 16.04 
Anaconda 3
DNNDK v3.0
DECENT_Q

但是我看了下xilinx-pynqz2-dpu3.0-pynq2.5.img裡的版本
Ubuntu 18.04
DNNDK v3.1
這是否意味著我無法照著這篇的內容去做

**Comment by wutianze** [comment]
> > > 我已經將xilinx-pynqz2-dpu3.0-pynq2.5.img燒進pynqz2裡面
> > > ![image](https://user-images.githubusercontent.com/74777370/105574235-1dbbe080-5d9e-11eb-812c-488a26af9baf.png)
> > > 但是沒有看到下面這張圖裡的文件
> > > ![image](https://user-images.githubusercontent.com/74777370/105574243-24e2ee80-5d9e-11eb-9b01-64b6122c8634.png)
> > > 我接下來應該把以下3個資料夾放進pynqz2裡面嗎?
> > > ![image](https://user-images.githubusercontent.com/74777370/105574244-29a7a280-5d9e-11eb-80b3-01cc3a1f9c56.png)
> > > 另外問個問題
> > > 我在jupyter_notebooks/resnet50 裡面找到
> > > ![image](https://user-images.githubusercontent.com/74777370/105574250-2f9d8380-5d9e-11eb-8fa1-a90b0c20b2ef.png)
> > > 執行到resnet50_cn.ipynb中的 run DPU and get the result
> > > ![image](https://user-images.githubusercontent.com/74777370/105574256-375d2800-5d9e-11eb-9b13-8f254ebdcb9c.png)
> > > 會造成
> > > 執行dpu後內核死亡所以自動重啟
> > > ![image](https://user-images.githubusercontent.com/74777370/105574259-42b05380-5d9e-11eb-94b1-b9461f907138.png)
> > > 我該如何使用這個dpu呢?
> > 
> > 
> > 如果你不是自己做镜像的话就不用管第一张图里那些文件了。如果是刚上手入门请按照文档的步骤来，等熟悉了再自己拓展。
> 
> 我照您的意見看了dnndk-pynqz2/mnist_tf/mnist_handwriting_guide.md這篇
> 
> 前置作業為
> Ubuntu 16.04
> Anaconda 3
> DNNDK v3.0
> DECENT_Q
> 
> 但是我看了下xilinx-pynqz2-dpu3.0-pynq2.5.img裡的版本
> Ubuntu 18.04
> DNNDK v3.1
> 這是否意味著我無法照著這篇的內容去做

ubuntu系统倒是影响不大，dnndk只要搭建成功，后面的步骤应该没有太多差别
