### ISSUE TITLE
制作镜像的文件从哪里下载呢？

### ISSUE THREAD

**Issue by B1D1ng** [wutianze/dnndk-pynqz2#15]
前辈你好，如果要自己制作镜像的话，教程里的那些文件在哪里下载呢？

**Comment by Sunshine2019a** [comment]
hello！请问你找到了吗？百度云盘只有做好的镜像

**Comment by wutianze** [comment]
> hello！请问你找到了吗？百度云盘只有做好的镜像

https://github.com/wutianze/dnndk-pynqz2/blob/master/build-pynqz2-system.md

**Comment by Sunshine2019a** [comment]
> > hello！请问你找到了吗？百度云盘只有做好的镜像
> 
> https://github.com/wutianze/dnndk-pynqz2/blob/master/build-pynqz2-system.md

作者您好！百度云盘里面只有一个做好的镜像，请问在哪找制作镜像的文件呢？我想自己走一遍流程。

**Comment by Sunshine2019a** [comment]
![image](https://user-images.githubusercontent.com/61735076/168714777-dd894379-3cae-4a0f-bfa7-119ed3b7433f.png)
就是这些文件，您还可以找到吗？

**Comment by wutianze** [comment]
> ![image](https://user-images.githubusercontent.com/61735076/168714777-dd894379-3cae-4a0f-bfa7-119ed3b7433f.png) 就是这些文件，您还可以找到吗？

镜像里应该有这些文件

**Comment by Sunshine2019a** [comment]
> > ![image](https://user-images.githubusercontent.com/61735076/168714777-dd894379-3cae-4a0f-bfa7-119ed3b7433f.png) 就是这些文件，您还可以找到吗？
> 
> 镜像里应该有这些文件

好的，谢谢您！
