### ISSUE TITLE
Using Mobilenet.

### ISSUE THREAD

**Issue by Schrodingerrs-cat** [wutianze/dnndk-pynqz2#17]
Hey, 
I am using Mobilenet which is already based on tensorflow, which should not require model conversion I think right? then should I proceed to directly Quantization?

**Comment by wutianze** [comment]
> Hey, I am using Mobilenet which is already based on tensorflow, which should not require model conversion I think right? then should I proceed to directly Quantization?

You are right, not need to do the conversion.

**Comment by MaRcOsss1** [comment]
So do you know where I can refer to scripts for quantization? or atleast I can get Idea how to quantize my mobilenet model?

**Comment by Schrodingerrs-cat** [comment]
So do you know where I can refer to scripts for quantization? or atleast I can get Idea how to quantize my mobilenet model?

**Comment by wutianze** [comment]
> So do you know where I can refer to scripts for quantization? or atleast I can get Idea how to quantize my mobilenet model?

You can check this: https://github.com/wutianze/pynq_car/blob/master/Pynq-Z2_AD_Car/host-guide/dnndk_usage.md

**Comment by Schrodingerrs-cat** [comment]
Those steps will work even for Mobilenet?

**Comment by wutianze** [comment]
> Those steps will work even for Mobilenet?

As long as Mobilenet is a TF model
