### ISSUE TITLE
train model

### ISSUE THREAD

**Issue by NaWeirui** [wutianze/dnndk-pynqz2#18]
您好，我在keras-yolo3目录中看到您的训练自己数据集的教程，但是没有找到train.py文件，您可以提供一下吗

**Comment by wutianze** [comment]
> 您好，我在keras-yolo3目录中看到您的训练自己数据集的教程，但是没有找到train.py文件，您可以提供一下吗

可以参考yolo官方的训练流程，我找了一个v3的版本，希望可以帮到您：https://github.com/qqwweee/keras-yolo3

**Comment by NaWeirui** [comment]
十分感谢，另外我想问一下您，我已经训了一个自己数据集的模型并转换为.pb文件，但是我是在TensorFlow1.15版本下训练和转换的，我想用您的量化脚本，但是报错Check whether your GraphDef-interpreting binary is up to date with your GraphDef-generating binary，我查看一下是TensorFlow版本不一致，那这样是不是我需要也使用tenserflow1.12去训练和转换模型，请问您当时遇到这个问题吗

**Comment by wutianze** [comment]
> 十分感谢，另外我想问一下您，我已经训了一个自己数据集的模型并转换为.pb文件，但是我是在TensorFlow1.15版本下训练和转换的，我想用您的量化脚本，但是报错Check whether your GraphDef-interpreting binary is up to date with your GraphDef-generating binary，我查看一下是TensorFlow版本不一致，那这样是不是我需要也使用tenserflow1.12去训练和转换模型，请问您当时遇到这个问题吗

对，需要转化到正确的tf版本，不然会出错（如果转换失败，那只能换正确的版本重新训练）。兼容性上目前好像没有太好的解决办法

**Comment by NaWeirui** [comment]
十分感谢您的回答！
