### ISSUE TITLE
Makefile timestamp Issue

### ISSUE THREAD

**Issue by Schrodingerrs-cat** [wutianze/dnndk-pynqz2#19]
Hey,

I was trying to run a makerfile on the MobaXterm Terminal, ran the "make" command and ran into an error. The error log:
```
root@pynqz2_dpu1:~# cd yolo_pynqz2
root@pynqz2_dpu1:~/yolo_pynqz2# make
make: Warning: File 'Makefile' has modification time 1200 s in the future
g++ -c -O2 -Wall -Wpointer-arith -std=c++11 -ffast-math -mcpu=cortex-a9 -mfloat-abi=hard -mfpu=neon programs/yolo_image.cpp -o objects/yolo_image.o
make: g++: Command not found
make: *** [Makefile:40: objects/yolo_image.o] Error 127
```
Now, I tried downloading the plugin for  g++: 
![image](https://github.com/user-attachments/assets/9649ac54-490f-4599-a5f7-c685b64cd906)

and placed it here: 
![image](https://github.com/user-attachments/assets/cbc3836e-8bc8-43bf-811a-17ae83e1d74c)

But I'm still facing the same problem, what possibly could I have done wrong?

**Comment by wutianze** [comment]
> Hey,
> 
> I was trying to run a makerfile on the MobaXterm Terminal, ran the "make" command and ran into an error. The error log:
> 
> ```
> root@pynqz2_dpu1:~# cd yolo_pynqz2
> root@pynqz2_dpu1:~/yolo_pynqz2# make
> make: Warning: File 'Makefile' has modification time 1200 s in the future
> g++ -c -O2 -Wall -Wpointer-arith -std=c++11 -ffast-math -mcpu=cortex-a9 -mfloat-abi=hard -mfpu=neon programs/yolo_image.cpp -o objects/yolo_image.o
> make: g++: Command not found
> make: *** [Makefile:40: objects/yolo_image.o] Error 127
> ```
> 
> Now, I tried downloading the plugin for g++: ![image](https://private-user-images.githubusercontent.com/123965986/352235634-9649ac54-490f-4599-a5f7-c685b64cd906.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5NTUwOTEsIm5iZiI6MTcyMTk1NDc5MSwicGF0aCI6Ii8xMjM5NjU5ODYvMzUyMjM1NjM0LTk2NDlhYzU0LTQ5MGYtNDU5OS1hNWY3LWM2ODViNjRjZDkwNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyNlQwMDQ2MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MWY3ZjRlZmQzYTI2NDI2NDMzMTdhNzNiNDMzYmMyNWU1YWI1YmE2MGFiOTVjNGU0ODUwZWE0NDEwZGRhMTNjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.sdZD0VxMqNSY2idDnp-HFbFXJ18SYhYZ7xqwPOjYLCg)
> 
> and placed it here: ![image](https://private-user-images.githubusercontent.com/123965986/352235656-cbc3836e-8bc8-43bf-811a-17ae83e1d74c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5NTUwOTEsIm5iZiI6MTcyMTk1NDc5MSwicGF0aCI6Ii8xMjM5NjU5ODYvMzUyMjM1NjU2LWNiYzM4MzZlLThiYzgtNDNiZi04MTFhLTE3YWU4M2UxZDc0Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyNlQwMDQ2MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NmI5NTYxZjg4ODg1ODA5MjBlNDFiZDQwMDc2NGQ2OTU4MjE4NzE1YjYzNTkxZDBkNTA0MmM2NTc5MzAyODFiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.VLbriLBT2TOCM2hwYZhllz8wdIgYpKkRi5it0DcIhdY)
> 
> But I'm still facing the same problem, what possibly could I have done wrong?

Hi, it seems like the timestamp of Makefile is wrong, try opening and saving it to update its timestamp
