### ISSUE TITLE
DNNDK run error

### ISSUE THREAD

**Issue by NarcissusYe** [wutianze/dnndk-pynqz2#2]
####################################################
Warning:                                            
The DPU in this TRD can only work 8 hours each time!
Please consult Sales for more details about this!   
####################################################

[DNNDK] fail to open DPU device and exit ...

it's the error report,should I compile a new linux system ?
what should i do?please

**Comment by wutianze** [comment]
Emmm, first you should check if dpu.ko has been loaded, if not, run su insmod /home/xilinx/dpu.ko. Then I don't actually understand why you need to compile a linux system, you mean build a penta-linux?

**Comment by LLLLHhhhh** [comment]
I can't log in with the username and password you provided .Could you please provide the correct one? please
