### ISSUE TITLE
The login problem

### ISSUE THREAD

**Issue by TnT0-0** [wutianze/dnndk-pynqz2#5]
I can't log in with the username and password you provided.Could you please provide the correct one?please

**Comment by wutianze** [comment]
You may check your input,, the one provided in docs is correct.

**Comment by TnT0-0** [comment]
I‘m sorry I still haven't solved the problem.The system I used is provided by your baidu cloud, and the username and password are both 'root'. Sorry to bother you, and thank you for your answer.

**Comment by wutianze** [comment]
Sorry, the content maybe unclear, if you use the downloaded file, the username is xilinx and the passwd is xilinx
