### ISSUE TITLE
Deploying a custom object detector

### ISSUE THREAD

**Issue by zackdilan** [wutianze/dnndk-pynqz2#7]
@wutianze I really appreciate your work, but I would like to get cleared of few details regarding my own network deployment on PYNQ Z2. I am completely new to FPGA and Xilinx software tools(But I understood the flow of deploying and using the DNNDK toolkit on a higher level). So my question is regarding the **build-pynqz2-system**. I have downloaded the image file from the link you have provided. if I have it, is it possible to skip all the steps mentioned in the build-pynqz2-system doc file? if not what should be done, I expect a clear explanation (how the pipeline flows ). I didn't mean your explanation is bad, I am not able to catch up.

Thanks in advance,
Zack

**Comment by wutianze** [comment]
Good news, if you have downloaded the image file, the only thing next is to burn it into the sd card. You can skip the steps in the .md, but I still recommend you read it.

**Comment by zackdilan** [comment]
Yes, I have gone through it. But I have a question regarding making the DPU overlay. The DPU IP should be a custom one right? Does the one correspond to the network that we are working with? Or the image that you have given can be used with any neural network?

**Comment by wutianze** [comment]
DPU can be used for any neural network(except for some unsupported layers).
You can read DNNDK doc for how to build your own elf file from trained model which can then be run in DPU.
The image I provided is based on DNNDKv3.0, it's general, you can run your own elf file in it.

**Comment by zackdilan** [comment]
Hey, I almost reached until the Yolo app demo. How long does this command take to run on the device `./yolo ./images/ i`.  It's taking a lot of time. Is it like that?

**Comment by wutianze** [comment]
Try running ./yolo dog.jpg? ./images will detect all the images, so maybe slow.

**Comment by zackdilan** [comment]
![pynq doubt](https://user-images.githubusercontent.com/50382476/80321055-6bf58080-881a-11ea-865b-f65c89988bd1.PNG)
What is wrong here?

**Comment by wutianze** [comment]
Sorry, the usage is ./yolo dog.jpg i

**Comment by zackdilan** [comment]
it throws an `error:dog.jpg is not a valid directory! ,`

**Comment by wutianze** [comment]
Oh, please put .jpg in a directory you created and then ./yolo ./your_dir/ i, but make sure there is only one image in the dir
