### ISSUE TITLE
Image Label on FPGA

### ISSUE THREAD

**Issue by FahriiEseenn** [wutianze/dnndk-pynqz2#8]
Can you help me about Image Label on FPGA? I produced a .pb model file using Darknet tutorial. And then convert it to the .elf file. But while I convert , there is no information about input shape.(input shape = [?, ? ,?,?]). And I wrote in decent_q as ?,224,224,3. Then I uploaded .elf file into the ZCU102 -> adas detection -> model file. And I am modified necessary parameters classnum, anchor, biases etc. Then I run the program. But there is no label on the image or video or cam. Why? Could it be due to input shape?

**Comment by wutianze** [comment]
Emm, I am sorry that I am not familiar with ZCU102 and may not provide much help. But I think the problem you met is not caused by the input shape, since '?' means you can input any shape. Maybe the photo you use doesn't contain the objects that can be detected by your model?

**Comment by FahriiEseenn** [comment]
I wanna train a model like you how can I train the model like you. Can you explain step by step? My graduation project is about DNNDK. But I did not train perfectly model like you. And also I am working ADAS Detection. Thanks a lot for your helping.

**Comment by wutianze** [comment]
You should refer to the guide in directory yolo_pynqz2_guide.md: https://github.com/wutianze/dnndk-pynqz2/blob/master/yolo_keras/yolo_pynqz2_guide.md. I provide many useful links there, or you can search online for some guidance and as I know there exist many websites that teach you how to train a yolo model.

**Comment by FahriiEseenn** [comment]
I am trained again a model using your training steps. But again my model's shape again is [?,?,?,3]. I think you are using different method in training. when I train a model using pjreddie(darknet) yolov3, model's input shape becomes [?,?,?,3].But your models shape is fixed. Are there any step to do this?

**Comment by wutianze** [comment]
I don't quite get your problem, it seems like you have finished training the model successfully.
