### ISSUE TITLE
有几个问题想请教一下

### ISSUE THREAD

**Issue by B1D1ng** [wutianze/dnndk-pynqz2#9]
1. 我在赛灵思的Vitis AI Zoo里发现赛灵思优化了Tensorflow框架和Darknet框架下的yolo模型，目前想将训练好的模型移植到PYNQ-Z2板子上然后做目标检测，请问例如tf框架下的，赛灵思的Zoo里的模型和源作者yunyang1994开源的tf_yolov3差别是否会很大？

2. 能否将yunyang1994的tf_yolov3模型根据自己的需求训练好后，直接量化裁剪移植到PYNQ-Z2板子上呢？

3.如果2不可行的话，那么赛灵思是否提供了他们自己优化后的模型训练教程？

我刚刚开始入门，对这几个问题比较困惑，希望作者能解答一下，感激不尽！

**Comment by wutianze** [comment]
不好意思，这个就不是很清楚了。但估计差别不大，Xilinx的yolo模型应该就是用的官方版本

**Comment by B1D1ng** [comment]
> 不好意思，这个就不是很清楚了。但估计差别不大，Xilinx的yolo模型应该就是用的官方版本

好的没关系，那您知道赛灵思的yolo模型如何去训练自定义数据集吗？我查阅了他们的User Guide和仓库里的各种Tutorial，暂时没有发现有提到如何去训练他们优化后的模型。如果您知道的话还请指引一下，感谢！

**Comment by wutianze** [comment]
官方的模型比较局限，没有yolo相关的部分。如何训练yolo模型网上应该有很多资料，只要把最终模型丢给dnndk就可以了。我这边有一个参考教程可以看一下：https://github.com/wutianze/dnndk-pynqz2

**Comment by B1D1ng** [comment]
> 官方的模型比较局限，没有yolo相关的部分。如何训练yolo模型网上应该有很多资料，只要把最终模型丢给dnndk就可以了。我这边有一个参考教程可以看一下：https://github.com/wutianze/dnndk-pynqz2

原来是这样！您的意思是我可以先找纯软的深度学习模型（例如Pytorch yolov3或者Tensorflow yolov3）根据我的需求利用数据集来进行训练，最后通过DNNDK量化编译进PYNQ-Z2这块板子上就可以了对吗？

另外我看了一下官方的AI仓库README，提到了支持ZCU104以及Ultra96那些高级板，PYNQ-Z2这块板子性能肯定是不如那些板子，但目前也支持DPU，可否能实现模型的移植呢？移植后性能暂时不考虑，只要能先移植即可。

**Comment by B1D1ng** [comment]
> 官方的模型比较局限，没有yolo相关的部分。如何训练yolo模型网上应该有很多资料，只要把最终模型丢给dnndk就可以了。我这边有一个参考教程可以看一下：https://github.com/wutianze/dnndk-pynqz2

您好，我看了您的仓库里的教程以及gitbook的内容，觉得非常棒！
想请问一下，您将yolov3模型移植进PYNQ-Z2板子上后，模型的性能损失了多少呢？这块板子的资源加上DPU是否能支持其进行目标检测？比如检测官方模型原本已经训练好的那些类别。
期待您的回复！谢谢！

**Comment by wutianze** [comment]
> > 官方的模型比较局限，没有yolo相关的部分。如何训练yolo模型网上应该有很多资料，只要把最终模型丢给dnndk就可以了。我这边有一个参考教程可以看一下：https://github.com/wutianze/dnndk-pynqz2
> 
> 原来是这样！您的意思是我可以先找纯软的深度学习模型（例如Pytorch yolov3或者Tensorflow yolov3）根据我的需求利用数据集来进行训练，最后通过DNNDK量化编译进PYNQ-Z2这块板子上就可以了对吗？
> 
> 另外我看了一下官方的AI仓库README，提到了支持ZCU104以及Ultra96那些高级板，PYNQ-Z2这块板子性能肯定是不如那些板子，但目前也支持DPU，可否能实现模型的移植呢？移植后性能暂时不考虑，只要能先移植即可。

对，目前我这一套东西支持keras和tensorflow，当然如果你有办法把其他模型转成.pb也ok。模型训练和dnndk是解耦的。Z2移植模型是没问题的，具体参考教程。

**Comment by wutianze** [comment]
> > 官方的模型比较局限，没有yolo相关的部分。如何训练yolo模型网上应该有很多资料，只要把最终模型丢给dnndk就可以了。我这边有一个参考教程可以看一下：https://github.com/wutianze/dnndk-pynqz2
> 
> 您好，我看了您的仓库里的教程以及gitbook的内容，觉得非常棒！
> 想请问一下，您将yolov3模型移植进PYNQ-Z2板子上后，模型的性能损失了多少呢？这块板子的资源加上DPU是否能支持其进行目标检测？比如检测官方模型原本已经训练好的那些类别。
> 期待您的回复！谢谢！

你这里的性能损失是指和96比较吗？性能有损失，具体得看你yolo需要分的类别。目标检测肯定可以啊。

**Comment by B1D1ng** [comment]
> > > 官方的模型比较局限，没有yolo相关的部分。如何训练yolo模型网上应该有很多资料，只要把最终模型丢给dnndk就可以了。我这边有一个参考教程可以看一下：https://github.com/wutianze/dnndk-pynqz2
> > 
> > 
> > 您好，我看了您的仓库里的教程以及gitbook的内容，觉得非常棒！
> > 想请问一下，您将yolov3模型移植进PYNQ-Z2板子上后，模型的性能损失了多少呢？这块板子的资源加上DPU是否能支持其进行目标检测？比如检测官方模型原本已经训练好的那些类别。
> > 期待您的回复！谢谢！
> 
> 你这里的性能损失是指和96比较吗？性能有损失，具体得看你yolo需要分的类别。目标检测肯定可以啊。

是的，我的模型是Tensorflow-Yolov3（基于YunYang1994的训练的），只训练识别两个类，没看到您的教程之前在赛灵思仓库和社区都没找到相关移植的内容，担心移植到Z2板子上后不能用。。。
之前了解到19年的时候Z2有一个QNN-MO-YOLO的项目，是Tinier-yolo，实时性3秒1帧。。
您移植Keras-yolo进去后测试实时性效果如何呢？

**Comment by B1D1ng** [comment]
> > > 官方的模型比较局限，没有yolo相关的部分。如何训练yolo模型网上应该有很多资料，只要把最终模型丢给dnndk就可以了。我这边有一个参考教程可以看一下：https://github.com/wutianze/dnndk-pynqz2
> > 
> > 
> > 您好，我看了您的仓库里的教程以及gitbook的内容，觉得非常棒！
> > 想请问一下，您将yolov3模型移植进PYNQ-Z2板子上后，模型的性能损失了多少呢？这块板子的资源加上DPU是否能支持其进行目标检测？比如检测官方模型原本已经训练好的那些类别。
> > 期待您的回复！谢谢！
> 
> 你这里的性能损失是指和96比较吗？性能有损失，具体得看你yolo需要分的类别。目标检测肯定可以啊。

不好意思再次打扰到您，我看了您的PYNQ-Car的gitbook教程，有一个地方不是很清楚，就是，将自己训练好的目标检测模型按照教程量化裁剪后生成elf文件，然后移到板子上，最后如何执行模型进行目标检测呢？运行模型的命令是否和在纯软框架下的命令一样？
教程里写的是“生成DPU可以识别的elf文件后，将项目与这个elf文件一同移动到板子上”，然后就直接run运行模型了。Car项目文件夹下有两个子文件夹，一个是model存放.elf，一个是src文件夹，这个文件夹下的文件好像也是另外生成的。

期待您的回复，谢谢！

**Comment by wutianze** [comment]
如果是完整的yolov3网络差不多3-5fps，如果是tiny-yolo网络能快很多。这和类别数量以及图片大小也会有一些关系。z2板子本身性能不算非常好，如果要追求速度建议换96

**Comment by wutianze** [comment]
https://app.gitbook.com/@1369130123/s/pynq-z2-ad-car/pynq-part/run_guide这里应该已经说明了怎么运行了。另外也可以参考一下这个https://github.com/wutianze/dnndk-pynqz2。板子上运行的指令肯定不会和软件框架的一样，那是在调用DNNDK库来去跑模型




------------------&nbsp;Original message&nbsp;------------------
From: "Huaxun Wu"; 
Sendtime: Wednesday, Aug 5, 2020 8:39 PM
To: "wutianze/dnndk-pynqz2"; 
Cc: "1369130123"<1369130123@qq.com>; "Comment"; 
Subject: Re: [wutianze/dnndk-pynqz2] 有几个问题想请教一下 (#9)





    
官方的模型比较局限，没有yolo相关的部分。如何训练yolo模型网上应该有很多资料，只要把最终模型丢给dnndk就可以了。我这边有一个参考教程可以看一下：https://github.com/wutianze/dnndk-pynqz2
  
您好，我看了您的仓库里的教程以及gitbook的内容，觉得非常棒！
 想请问一下，您将yolov3模型移植进PYNQ-Z2板子上后，模型的性能损失了多少呢？这块板子的资源加上DPU是否能支持其进行目标检测？比如检测官方模型原本已经训练好的那些类别。
 期待您的回复！谢谢！
  
你这里的性能损失是指和96比较吗？性能有损失，具体得看你yolo需要分的类别。目标检测肯定可以啊。
  
不好意思再次打扰到您，我看了您的PYNQ-Car的gitbook教程，有一个地方不是很清楚，就是，将自己训练好的目标检测模型按照教程量化裁剪后生成elf文件，然后移到板子上，最后如何执行模型进行目标检测呢？运行模型的命令是否和在纯软框架下的命令一样？
 教程里写的是“生成DPU可以识别的elf文件后，将项目与这个elf文件一同移动到板子上”，然后就直接run运行模型了。Car项目文件夹下有两个子文件夹，一个是model存放.elf，一个是src文件夹，这个文件夹下的文件好像也是另外生成的。
 
期待您的回复，谢谢！

**Comment by B1D1ng** [comment]
> [https://app.gitbook.com/@1369130123/s/pynq-z2-ad-car/pynq-part/run_guide这里应该已经说明了怎么运行了。另外也可以参考一下这个https://github.com/wutianze/dnndk-pynqz2。板子上运行的指令肯定不会和软件框架的一样，那是在调用DNNDK库来去跑模型](https://app.gitbook.com/@1369130123/s/pynq-z2-ad-car/pynq-part/run_guide%E8%BF%99%E9%87%8C%E5%BA%94%E8%AF%A5%E5%B7%B2%E7%BB%8F%E8%AF%B4%E6%98%8E%E4%BA%86%E6%80%8E%E4%B9%88%E8%BF%90%E8%A1%8C%E4%BA%86%E3%80%82%E5%8F%A6%E5%A4%96%E4%B9%9F%E5%8F%AF%E4%BB%A5%E5%8F%82%E8%80%83%E4%B8%80%E4%B8%8B%E8%BF%99%E4%B8%AAhttps://github.com/wutianze/dnndk-pynqz2%E3%80%82%E6%9D%BF%E5%AD%90%E4%B8%8A%E8%BF%90%E8%A1%8C%E7%9A%84%E6%8C%87%E4%BB%A4%E8%82%AF%E5%AE%9A%E4%B8%8D%E4%BC%9A%E5%92%8C%E8%BD%AF%E4%BB%B6%E6%A1%86%E6%9E%B6%E7%9A%84%E4%B8%80%E6%A0%B7%EF%BC%8C%E9%82%A3%E6%98%AF%E5%9C%A8%E8%B0%83%E7%94%A8DNNDK%E5%BA%93%E6%9D%A5%E5%8E%BB%E8%B7%91%E6%A8%A1%E5%9E%8B)
> […](#)
> ------------------&nbsp;Original message&nbsp;------------------ From: "Huaxun Wu"; Sendtime: Wednesday, Aug 5, 2020 8:39 PM To: "wutianze/dnndk-pynqz2"; Cc: "1369130123"<1369130123@qq.com>; "Comment"; Subject: Re: [wutianze/dnndk-pynqz2] 有几个问题想请教一下 (#9) 官方的模型比较局限，没有yolo相关的部分。如何训练yolo模型网上应该有很多资料，只要把最终模型丢给dnndk就可以了。我这边有一个参考教程可以看一下：https://github.com/wutianze/dnndk-pynqz2 您好，我看了您的仓库里的教程以及gitbook的内容，觉得非常棒！ 想请问一下，您将yolov3模型移植进PYNQ-Z2板子上后，模型的性能损失了多少呢？这块板子的资源加上DPU是否能支持其进行目标检测？比如检测官方模型原本已经训练好的那些类别。 期待您的回复！谢谢！ 你这里的性能损失是指和96比较吗？性能有损失，具体得看你yolo需要分的类别。目标检测肯定可以啊。 不好意思再次打扰到您，我看了您的PYNQ-Car的gitbook教程，有一个地方不是很清楚，就是，将自己训练好的目标检测模型按照教程量化裁剪后生成elf文件，然后移到板子上，最后如何执行模型进行目标检测呢？运行模型的命令是否和在纯软框架下的命令一样？ 教程里写的是“生成DPU可以识别的elf文件后，将项目与这个elf文件一同移动到板子上”，然后就直接run运行模型了。Car项目文件夹下有两个子文件夹，一个是model存放.elf，一个是src文件夹，这个文件夹下的文件好像也是另外生成的。 期待您的回复，谢谢！ — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

您好，我在使用您的镜像过程中，发现好像这个镜像并没有完全支持官方对应版本镜像的overlay功能，比如hdmi功能，如果我想要用这些功能的话，只能自己重新制作镜像吗

**Comment by wutianze** [comment]
嗯，如果有这些需求而目前这个镜像没有的话那只能重新做了。印象中xilinx可能会或者已经放出了最新的支持dnndk与overlay的镜像吧，但也可能fpga面积不够，所以不能兼顾。具体就不太清楚了。

**Comment by wutianze** [comment]
> > [https://app.gitbook.com/@1369130123/s/pynq-z2-ad-car/pynq-part/run_guide这里应该已经说明了怎么运行了。另外也可以参考一下这个https://github.com/wutianze/dnndk-pynqz2。板子上运行的指令肯定不会和软件框架的一样，那是在调用DNNDK库来去跑模型](https://app.gitbook.com/@1369130123/s/pynq-z2-ad-car/pynq-part/run_guide%E8%BF%99%E9%87%8C%E5%BA%94%E8%AF%A5%E5%B7%B2%E7%BB%8F%E8%AF%B4%E6%98%8E%E4%BA%86%E6%80%8E%E4%B9%88%E8%BF%90%E8%A1%8C%E4%BA%86%E3%80%82%E5%8F%A6%E5%A4%96%E4%B9%9F%E5%8F%AF%E4%BB%A5%E5%8F%82%E8%80%83%E4%B8%80%E4%B8%8B%E8%BF%99%E4%B8%AAhttps://github.com/wutianze/dnndk-pynqz2%E3%80%82%E6%9D%BF%E5%AD%90%E4%B8%8A%E8%BF%90%E8%A1%8C%E7%9A%84%E6%8C%87%E4%BB%A4%E8%82%AF%E5%AE%9A%E4%B8%8D%E4%BC%9A%E5%92%8C%E8%BD%AF%E4%BB%B6%E6%A1%86%E6%9E%B6%E7%9A%84%E4%B8%80%E6%A0%B7%EF%BC%8C%E9%82%A3%E6%98%AF%E5%9C%A8%E8%B0%83%E7%94%A8DNNDK%E5%BA%93%E6%9D%A5%E5%8E%BB%E8%B7%91%E6%A8%A1%E5%9E%8B)
> > […](#)
> > ------------------ Original message ------------------ From: "Huaxun Wu"; Sendtime: Wednesday, Aug 5, 2020 8:39 PM To: "wutianze/dnndk-pynqz2"; Cc: "1369130123"[1369130123@qq.com](mailto:1369130123@qq.com); "Comment"; Subject: Re: [wutianze/dnndk-pynqz2] 有几个问题想请教一下 (#9) 官方的模型比较局限，没有yolo相关的部分。如何训练yolo模型网上应该有很多资料，只要把最终模型丢给dnndk就可以了。我这边有一个参考教程可以看一下：https://github.com/wutianze/dnndk-pynqz2 您好，我看了您的仓库里的教程以及gitbook的内容，觉得非常棒！ 想请问一下，您将yolov3模型移植进PYNQ-Z2板子上后，模型的性能损失了多少呢？这块板子的资源加上DPU是否能支持其进行目标检测？比如检测官方模型原本已经训练好的那些类别。 期待您的回复！谢谢！ 你这里的性能损失是指和96比较吗？性能有损失，具体得看你yolo需要分的类别。目标检测肯定可以啊。 不好意思再次打扰到您，我看了您的PYNQ-Car的gitbook教程，有一个地方不是很清楚，就是，将自己训练好的目标检测模型按照教程量化裁剪后生成elf文件，然后移到板子上，最后如何执行模型进行目标检测呢？运行模型的命令是否和在纯软框架下的命令一样？ 教程里写的是“生成DPU可以识别的elf文件后，将项目与这个elf文件一同移动到板子上”，然后就直接run运行模型了。Car项目文件夹下有两个子文件夹，一个是model存放.elf，一个是src文件夹，这个文件夹下的文件好像也是另外生成的。 期待您的回复，谢谢！ — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.
> 
> 您好，我在使用您的镜像过程中，发现好像这个镜像并没有完全支持官方对应版本镜像的overlay功能，比如hdmi功能，如果我想要用这些功能的话，只能自己重新制作镜像吗

嗯，如果有这些需求而目前这个镜像没有的话那只能重新做了。印象中xilinx可能会或者已经放出了最新的支持dnndk与overlay的镜像吧，但也可能fpga面积不够，所以不能兼顾。具体就不太清楚了。

**Comment by B1D1ng** [comment]
> > > [https://app.gitbook.com/@1369130123/s/pynq-z2-ad-car/pynq-part/run_guide这里应该已经说明了怎么运行了。另外也可以参考一下这个https://github.com/wutianze/dnndk-pynqz2。板子上运行的指令肯定不会和软件框架的一样，那是在调用DNNDK库来去跑模型](https://app.gitbook.com/@1369130123/s/pynq-z2-ad-car/pynq-part/run_guide%E8%BF%99%E9%87%8C%E5%BA%94%E8%AF%A5%E5%B7%B2%E7%BB%8F%E8%AF%B4%E6%98%8E%E4%BA%86%E6%80%8E%E4%B9%88%E8%BF%90%E8%A1%8C%E4%BA%86%E3%80%82%E5%8F%A6%E5%A4%96%E4%B9%9F%E5%8F%AF%E4%BB%A5%E5%8F%82%E8%80%83%E4%B8%80%E4%B8%8B%E8%BF%99%E4%B8%AAhttps://github.com/wutianze/dnndk-pynqz2%E3%80%82%E6%9D%BF%E5%AD%90%E4%B8%8A%E8%BF%90%E8%A1%8C%E7%9A%84%E6%8C%87%E4%BB%A4%E8%82%AF%E5%AE%9A%E4%B8%8D%E4%BC%9A%E5%92%8C%E8%BD%AF%E4%BB%B6%E6%A1%86%E6%9E%B6%E7%9A%84%E4%B8%80%E6%A0%B7%EF%BC%8C%E9%82%A3%E6%98%AF%E5%9C%A8%E8%B0%83%E7%94%A8DNNDK%E5%BA%93%E6%9D%A5%E5%8E%BB%E8%B7%91%E6%A8%A1%E5%9E%8B)
> > > […](#)
> > > ------------------ Original message ------------------ From: "Huaxun Wu"; Sendtime: Wednesday, Aug 5, 2020 8:39 PM To: "wutianze/dnndk-pynqz2"; Cc: "1369130123"[1369130123@qq.com](mailto:1369130123@qq.com); "Comment"; Subject: Re: [wutianze/dnndk-pynqz2] 有几个问题想请教一下 (#9) 官方的模型比较局限，没有yolo相关的部分。如何训练yolo模型网上应该有很多资料，只要把最终模型丢给dnndk就可以了。我这边有一个参考教程可以看一下：https://github.com/wutianze/dnndk-pynqz2 您好，我看了您的仓库里的教程以及gitbook的内容，觉得非常棒！ 想请问一下，您将yolov3模型移植进PYNQ-Z2板子上后，模型的性能损失了多少呢？这块板子的资源加上DPU是否能支持其进行目标检测？比如检测官方模型原本已经训练好的那些类别。 期待您的回复！谢谢！ 你这里的性能损失是指和96比较吗？性能有损失，具体得看你yolo需要分的类别。目标检测肯定可以啊。 不好意思再次打扰到您，我看了您的PYNQ-Car的gitbook教程，有一个地方不是很清楚，就是，将自己训练好的目标检测模型按照教程量化裁剪后生成elf文件，然后移到板子上，最后如何执行模型进行目标检测呢？运行模型的命令是否和在纯软框架下的命令一样？ 教程里写的是“生成DPU可以识别的elf文件后，将项目与这个elf文件一同移动到板子上”，然后就直接run运行模型了。Car项目文件夹下有两个子文件夹，一个是model存放.elf，一个是src文件夹，这个文件夹下的文件好像也是另外生成的。 期待您的回复，谢谢！ — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.
> > 
> > 
> > 您好，我在使用您的镜像过程中，发现好像这个镜像并没有完全支持官方对应版本镜像的overlay功能，比如hdmi功能，如果我想要用这些功能的话，只能自己重新制作镜像吗
> 
> 嗯，如果有这些需求而目前这个镜像没有的话那只能重新做了。印象中xilinx可能会或者已经放出了最新的支持dnndk与overlay的镜像吧，但也可能fpga面积不够，所以不能兼顾。具体就不太清楚了。

作者您好，请问您在制作镜像文件的时候，gcc/g++和Opencv是在制作镜像过程中加入的吗

**Comment by wutianze** [comment]
> > > > [https://app.gitbook.com/@1369130123/s/pynq-z2-ad-car/pynq-part/run_guide这里应该已经说明了怎么运行了。另外也可以参考一下这个https://github.com/wutianze/dnndk-pynqz2。板子上运行的指令肯定不会和软件框架的一样，那是在调用DNNDK库来去跑模型](https://app.gitbook.com/@1369130123/s/pynq-z2-ad-car/pynq-part/run_guide%E8%BF%99%E9%87%8C%E5%BA%94%E8%AF%A5%E5%B7%B2%E7%BB%8F%E8%AF%B4%E6%98%8E%E4%BA%86%E6%80%8E%E4%B9%88%E8%BF%90%E8%A1%8C%E4%BA%86%E3%80%82%E5%8F%A6%E5%A4%96%E4%B9%9F%E5%8F%AF%E4%BB%A5%E5%8F%82%E8%80%83%E4%B8%80%E4%B8%8B%E8%BF%99%E4%B8%AAhttps://github.com/wutianze/dnndk-pynqz2%E3%80%82%E6%9D%BF%E5%AD%90%E4%B8%8A%E8%BF%90%E8%A1%8C%E7%9A%84%E6%8C%87%E4%BB%A4%E8%82%AF%E5%AE%9A%E4%B8%8D%E4%BC%9A%E5%92%8C%E8%BD%AF%E4%BB%B6%E6%A1%86%E6%9E%B6%E7%9A%84%E4%B8%80%E6%A0%B7%EF%BC%8C%E9%82%A3%E6%98%AF%E5%9C%A8%E8%B0%83%E7%94%A8DNNDK%E5%BA%93%E6%9D%A5%E5%8E%BB%E8%B7%91%E6%A8%A1%E5%9E%8B)
> > > > […](#)
> > > > ------------------ Original message ------------------ From: "Huaxun Wu"; Sendtime: Wednesday, Aug 5, 2020 8:39 PM To: "wutianze/dnndk-pynqz2"; Cc: "1369130123"[1369130123@qq.com](mailto:1369130123@qq.com); "Comment"; Subject: Re: [wutianze/dnndk-pynqz2] 有几个问题想请教一下 (#9) 官方的模型比较局限，没有yolo相关的部分。如何训练yolo模型网上应该有很多资料，只要把最终模型丢给dnndk就可以了。我这边有一个参考教程可以看一下：https://github.com/wutianze/dnndk-pynqz2 您好，我看了您的仓库里的教程以及gitbook的内容，觉得非常棒！ 想请问一下，您将yolov3模型移植进PYNQ-Z2板子上后，模型的性能损失了多少呢？这块板子的资源加上DPU是否能支持其进行目标检测？比如检测官方模型原本已经训练好的那些类别。 期待您的回复！谢谢！ 你这里的性能损失是指和96比较吗？性能有损失，具体得看你yolo需要分的类别。目标检测肯定可以啊。 不好意思再次打扰到您，我看了您的PYNQ-Car的gitbook教程，有一个地方不是很清楚，就是，将自己训练好的目标检测模型按照教程量化裁剪后生成elf文件，然后移到板子上，最后如何执行模型进行目标检测呢？运行模型的命令是否和在纯软框架下的命令一样？ 教程里写的是“生成DPU可以识别的elf文件后，将项目与这个elf文件一同移动到板子上”，然后就直接run运行模型了。Car项目文件夹下有两个子文件夹，一个是model存放.elf，一个是src文件夹，这个文件夹下的文件好像也是另外生成的。 期待您的回复，谢谢！ — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.
> > > 
> > > 
> > > 您好，我在使用您的镜像过程中，发现好像这个镜像并没有完全支持官方对应版本镜像的overlay功能，比如hdmi功能，如果我想要用这些功能的话，只能自己重新制作镜像吗
> > 
> > 
> > 嗯，如果有这些需求而目前这个镜像没有的话那只能重新做了。印象中xilinx可能会或者已经放出了最新的支持dnndk与overlay的镜像吧，但也可能fpga面积不够，所以不能兼顾。具体就不太清楚了。
> 
> 作者您好，请问您在制作镜像文件的时候，gcc/g++和Opencv是在制作镜像过程中加入的吗

具体见制作镜像的文档吧，我也是照着那个来的
